name: Metrics
on:
  # Schedule updates (once a day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options to match your screenshot
          user: weenaath
          template: classic
          base: header, repositories  # This enables the "Contributed to" list
          config_timezone: Asia/Colombo
          
          # 1. The Calendar (The "Map" you want)
          plugin_calendar: yes
          plugin_calendar_limit: 1

          # 2. The Radar Chart (Activity Overview)
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
